export const GET_WEATHER_CONFIG = 'GET_WEATHER_CONFIG';
export const GET_WEATHER_CONFIG_PENDING = 'GET_WEATHER_CONFIG_PENDING';
export const GET_WEATHER_CONFIG_SUCCESS = 'GET_WEATHER_CONFIG_SUCCESS';
export const GET_WEATHER_CONFIG_FAILED = 'GET_WEATHER_CONFIG_FAILED';